const TRIVIA_BANK = [
{q:“Which US president was known as Teflon Ron because nothing bad seemed to stick to him?”,a:“Ronald Reagan”},
{q:“The Berlin Wall fell in which year?”,a:“1989”},
{q:“Which ancient wonder was located in Alexandria, Egypt?”,a:“The Lighthouse of Alexandria”},
{q:“Napoleon Bonaparte was born on which island?”,a:“Corsica”},
{q:“Which country gave the Statue of Liberty to the United States?”,a:“France”},
{q:“The Titanic sank in which year?”,a:“1912”},
{q:“Who was the first woman to win a Nobel Prize?”,a:“Marie Curie”},
{q:“Which empire was ruled by Genghis Khan?”,a:“The Mongol Empire”},
{q:“In what year did US women first get the right to vote?”,a:“1920”},
{q:“Which ancient civilisation built Machu Picchu?”,a:“The Inca”},
{q:“The French Revolution began in what year?”,a:“1789”},
{q:“Who was the last Pharaoh of Ancient Egypt?”,a:“Cleopatra VII”},
{q:“What was the name of the ship Charles Darwin sailed on?”,a:“HMS Beagle”},
{q:“Who assassinated Archduke Franz Ferdinand triggering WW1?”,a:“Gavrilo Princip”},
{q:“The Magna Carta was signed in which year?”,a:“1215”},
{q:“Which US president served just 31 days in office?”,a:“William Henry Harrison”},
{q:“The Cold War was primarily between the US and which nation?”,a:“Soviet Union”},
{q:“Who wrote the Communist Manifesto?”,a:“Karl Marx and Friedrich Engels”},
{q:“Julius Caesar was assassinated on what date now called?”,a:“The Ides of March”},
{q:“Which US state was the last to join the union?”,a:“Hawaii”},
{q:“The Cuban Missile Crisis occurred in which year?”,a:“1962”},
{q:“Who was the first person to walk on the moon?”,a:“Neil Armstrong”},
{q:“Which country held apartheid as official policy until 1994?”,a:“South Africa”},
{q:“The Boston Tea Party was a protest against taxes on what?”,a:“Tea”},
{q:“How many US presidents have been assassinated in office?”,a:“Four”},
{q:“Who was the first female Prime Minister of the UK?”,a:“Margaret Thatcher”},
{q:“In which city was the first atomic bomb dropped in 1945?”,a:“Hiroshima”},
{q:“Which war is called The War to End All Wars?”,a:“World War I”},
{q:“The Great Wall of China was built primarily to keep out whom?”,a:“Mongols and northern nomads”},
{q:“Which US war resulted in the most American deaths?”,a:“The Civil War”},
{q:“What is the only metal that is liquid at room temperature?”,a:“Mercury”},
{q:“How many bones does an adult human body have?”,a:“206”},
{q:“What planet has the most moons?”,a:“Saturn”},
{q:“What is the approximate speed of light in km per second?”,a:“300,000 km/s”},
{q:“What is the most abundant gas in Earth’s atmosphere?”,a:“Nitrogen”},
{q:“How many hearts does an octopus have?”,a:“Three”},
{q:“Which element has the atomic number 1?”,a:“Hydrogen”},
{q:“What is the hardest natural substance on Earth?”,a:“Diamond”},
{q:“Which planet rotates on its side with a tilt of about 98 degrees?”,a:“Uranus”},
{q:“What is the most common blood type in humans?”,a:“O positive”},
{q:“A group of flamingos is called a what?”,a:“A flamboyance”},
{q:“What is the smallest planet in our solar system?”,a:“Mercury”},
{q:“How many chromosomes do humans have?”,a:“46”},
{q:“What is the chemical symbol for gold?”,a:“Au”},
{q:“Which animal sleeps with one eye open and half its brain awake?”,a:“Dolphins”},
{q:“What percentage of the human body is water?”,a:“About 60%”},
{q:“What is the largest organ in the human body?”,a:“Skin”},
{q:“Sound travels faster through air or water?”,a:“Water”},
{q:“What is the closest star to Earth besides the Sun?”,a:“Proxima Centauri”},
{q:“What colour is a polar bear’s skin under its white fur?”,a:“Black”},
{q:“How long does light from the Sun take to reach Earth?”,a:“About 8 minutes”},
{q:“What animal has the largest eyes of any land animal?”,a:“Ostrich”},
{q:“Which blood type is the universal donor?”,a:“O negative”},
{q:“What is the bone in your upper arm called?”,a:“Humerus”},
{q:“What is the most venomous animal in the world?”,a:“Box jellyfish”},
{q:“How many teeth does an adult human have?”,a:“32”},
{q:“What gas do plants absorb during photosynthesis?”,a:“Carbon dioxide”},
{q:“Which pop star performed at the 2023 Super Bowl halftime show?”,a:“Rihanna”},
{q:“What fictional school does Harry Potter attend?”,a:“Hogwarts”},
{q:“Which TV show features the fictional Dunder Mifflin Paper Company?”,a:“The Office”},
{q:“Bohemian Rhapsody is a song by which band?”,a:“Queen”},
{q:“What year did the first iPhone launch?”,a:“2007”},
{q:“Which actress played Katniss Everdeen in The Hunger Games?”,a:“Jennifer Lawrence”},
{q:“What is the name of Tony Stark’s AI assistant in Iron Man?”,a:“JARVIS”},
{q:“Who sang Bad Guy?”,a:“Billie Eilish”},
{q:“What is the highest-grossing film of all time not adjusted for inflation?”,a:“Avatar”},
{q:“Which TV show made Winter is Coming famous?”,a:“Game of Thrones”},
{q:“What band was Beyoncé in before going solo?”,a:“Destiny’s Child”},
{q:“What is the name of Sherlock Holmes’s address?”,a:“221B Baker Street”},
{q:“Which movie won Best Picture at the 2020 Academy Awards?”,a:“Parasite”},
{q:“Which director made Pulp Fiction?”,a:“Quentin Tarantino”},
{q:“What colour is SpongeBob SquarePants?”,a:“Yellow”},
{q:“Which celebrity wore a meat dress to the 2010 MTV VMAs?”,a:“Lady Gaga”},
{q:“Who played James Bond the most times in film?”,a:“Roger Moore”},
{q:“What is the name of the dragon in The Hobbit?”,a:“Smaug”},
{q:“Kim Kardashian broke the internet in 2014 posing for which magazine?”,a:“Paper Magazine”},
{q:“Which pop star sang Oops I Did It Again?”,a:“Britney Spears”},
{q:“What actress played Elle Woods in Legally Blonde?”,a:“Reese Witherspoon”},
{q:“Which famous diva was known as The Queen of Soul?”,a:“Aretha Franklin”},
{q:“What movie features the line You can’t handle the truth?”,a:“A Few Good Men”},
{q:“What year did Breaking Bad first air?”,a:“2008”},
{q:“Who sang Rolling in the Deep?”,a:“Adele”},
{q:“What superhero is known as The Caped Crusader?”,a:“Batman”},
{q:“What Disney film features the song Let It Go?”,a:“Frozen”},
{q:“Which TV show is set in a fictional place called Pawnee Indiana?”,a:“Parks and Recreation”},
{q:“What is the name of the spaceship in the original Alien film?”,a:“The Nostromo”},
{q:“What year did Friends end?”,a:“2004”},
{q:“Who played Iron Man in the Marvel Cinematic Universe?”,a:“Robert Downey Jr”},
{q:“What is the longest river in the world?”,a:“The Nile”},
{q:“Which country has the most natural lakes?”,a:“Canada”},
{q:“What is the capital of Australia?”,a:“Canberra”},
{q:“Which ocean is the largest?”,a:“Pacific Ocean”},
{q:“What country has more pyramids than Egypt?”,a:“Sudan”},
{q:“What is the smallest country in the world?”,a:“Vatican City”},
{q:“The Ring of Fire circles which ocean?”,a:“Pacific Ocean”},
{q:“What is the capital of Canada?”,a:“Ottawa”},
{q:“What is the official language of Brazil?”,a:“Portuguese”},
{q:“What is the deepest lake in the world?”,a:“Lake Baikal”},
{q:“Which US state is the largest by area?”,a:“Alaska”},
{q:“What country has the most UNESCO World Heritage Sites?”,a:“Italy”},
{q:“What is the tallest mountain in the world?”,a:“Mount Everest”},
{q:“What is the capital of Japan?”,a:“Tokyo”},
{q:“Which country is known as the Land of the Rising Sun?”,a:“Japan”},
{q:“What is the capital of Argentina?”,a:“Buenos Aires”},
{q:“In which country is the Taj Mahal located?”,a:“India”},
{q:“Which country has the longest coastline in the world?”,a:“Canada”},
{q:“What is the currency of Japan?”,a:“The Yen”},
{q:“Which city is known as the City of Canals?”,a:“Venice”},
{q:“How many countries are in Africa?”,a:“54”},
{q:“What country invented champagne?”,a:“France”},
{q:“Which river runs through Egypt?”,a:“The Nile”},
{q:“What is the most spoken language in South America by number of speakers?”,a:“Portuguese”},
{q:“What is the main ingredient in guacamole?”,a:“Avocado”},
{q:“Which country invented sushi?”,a:“Japan”},
{q:“What is the most expensive spice by weight?”,a:“Saffron”},
{q:“What nut is used to make marzipan?”,a:“Almonds”},
{q:“What is the Japanese word for cheers when drinking?”,a:“Kanpai”},
{q:“What type of pastry makes a croissant?”,a:“Laminated pastry”},
{q:“What is the primary ingredient in hummus?”,a:“Chickpeas”},
{q:“Which country produces the most coffee in the world?”,a:“Brazil”},
{q:“What grain is used to make most Japanese sake?”,a:“Rice”},
{q:“Which country did the croissant actually originate from?”,a:“Austria”},
{q:“What cocktail contains gin lemon juice sugar and soda?”,a:“Tom Collins”},
{q:“What is the main difference between jam and marmalade?”,a:“Marmalade uses citrus peel”},
{q:“What ingredient makes Worcestershire sauce unusual?”,a:“Fermented anchovies”},
{q:“How many glasses of wine are in a standard bottle?”,a:“About five”},
{q:“What country invented pizza?”,a:“Italy”},
{q:“What is a Margherita pizza topped with?”,a:“Tomato mozzarella and basil”},
{q:“Who wrote Pride and Prejudice?”,a:“Jane Austen”},
{q:“What is the most translated book in the world?”,a:“The Bible”},
{q:“How many plays did Shakespeare write?”,a:“37”},
{q:“Which language has the most native speakers?”,a:“Mandarin Chinese”},
{q:“What does RSVP stand for?”,a:“Respondez s’il vous plait”},
{q:“1984 was written by which author?”,a:“George Orwell”},
{q:“Which letter is most common in the English language?”,a:“E”},
{q:“Who wrote Frankenstein?”,a:“Mary Shelley”},
{q:“Who created Hercule Poirot?”,a:“Agatha Christie”},
{q:“What is the name of the narrator in Moby Dick?”,a:“Ishmael”},
{q:“Who wrote The Great Gatsby?”,a:“F. Scott Fitzgerald”},
{q:“In what language was Don Quixote originally written?”,a:“Spanish”},
{q:“What is the longest word in common English use?”,a:“Pneumonoultramicroscopicsilicovolcanoconiosis”},
{q:“How many players are on a basketball team on the court at once?”,a:“Five”},
{q:“The FIFA World Cup is held every how many years?”,a:“Four”},
{q:“What country has won the most FIFA World Cups?”,a:“Brazil”},
{q:“In tennis what is a score of zero called?”,a:“Love”},
{q:“How long is a marathon in kilometres?”,a:“42.195”},
{q:“What sport is played at Wimbledon?”,a:“Tennis”},
{q:“Who invented basketball?”,a:“James Naismith”},
{q:“How many rings are on the Olympic flag?”,a:“Five”},
{q:“What sport uses a shuttlecock?”,a:“Badminton”},
{q:“How many gold medals did Michael Phelps win in his Olympic career?”,a:“23”},
{q:“What is the name of the trophy given to the Super Bowl winner?”,a:“The Vince Lombardi Trophy”},
{q:“In which sport do competitors perform a Triple Axel?”,a:“Figure skating”},
{q:“How many players are on a soccer team on the field?”,a:“Eleven”},
{q:“What sport features a scrimmage line and a quarterback?”,a:“American football”},
{q:“A group of crows is called a what?”,a:“A murder”},
{q:“What is the fear of long words called?”,a:“Hippopotomonstrosesquippedaliophobia”},
{q:“Which animal cannot jump?”,a:“Elephant”},
{q:“Humans share approximately 60 percent of DNA with what?”,a:“Bananas”},
{q:“What is the only food that never spoils?”,a:“Honey”},
{q:“A cockroach can survive how long without its head?”,a:“About a week”},
{q:“Which country has the most vending machines per capita?”,a:“Japan”},
{q:“What is the loudest animal on Earth?”,a:“Sperm whale”},
{q:“A day on Venus is longer than a year on Venus — true or false?”,a:“True”},
{q:“Cleopatra lived closer in time to the Moon landing than to the Great Pyramid — true or false?”,a:“True”},
{q:“What colour is a black box on an aeroplane?”,a:“Orange”},
{q:“A snail can sleep for how long?”,a:“Up to three years”},
{q:“What is the national animal of Scotland?”,a:“The unicorn”},
{q:“Wombats produce what unusually shaped droppings?”,a:“Cube-shaped”},
{q:“How many bones does a shark have?”,a:“Zero — only cartilage”},
{q:“What is the shortest war in history?”,a:“The Anglo-Zanzibar War at 38 minutes”},
{q:“What do you call a group of unicorns?”,a:“A blessing”},
{q:“What country’s flag is the only one that is not rectangular or square?”,a:“Nepal”},
{q:“Which language has no word for please or thank you in formal usage?”,a:“Many — including Mandarin in traditional usage”},
{q:“What percentage of the ocean remains unexplored by humans?”,a:“About 80 percent”},
{q:“Who painted the Mona Lisa?”,a:“Leonardo da Vinci”},
{q:“The musical Hamilton is about which Founding Father?”,a:“Alexander Hamilton”},
{q:“Which artist famously cut off his own ear?”,a:“Vincent van Gogh”},
{q:“What gallery houses the Mona Lisa?”,a:“The Louvre”},
{q:“Who designed the Eiffel Tower?”,a:“Gustave Eiffel”},
{q:“What art movement was Salvador Dali associated with?”,a:“Surrealism”},
{q:“Who designed the Guggenheim Museum in Bilbao?”,a:“Frank Gehry”},
{q:“What nationality was Frida Kahlo?”,a:“Mexican”},
{q:“Who painted the Sistine Chapel ceiling?”,a:“Michelangelo”},
{q:“What year was Facebook founded?”,a:“2004”},
{q:“What does AI stand for?”,a:“Artificial Intelligence”},
{q:“Who co-founded Apple with Steve Jobs?”,a:“Steve Wozniak”},
{q:“What does HTTP stand for?”,a:“HyperText Transfer Protocol”},
{q:“What is the name of Elon Musk’s space company?”,a:“SpaceX”},
{q:“What year was the first video game Pong released?”,a:“1972”},
{q:“What does PDF stand for?”,a:“Portable Document Format”},
{q:“Which company created the Android operating system?”,a:“Google”},
{q:“What year was Twitter now X founded?”,a:“2006”},
{q:“What does GPS stand for?”,a:“Global Positioning System”},
{q:“What is the most-used programming language in the world?”,a:“JavaScript”},
{q:“What tech company’s logo is a bitten apple?”,a:“Apple”},
{q:“Which planet is known as the Red Planet?”,a:“Mars”},
{q:“What is the chemical formula for water?”,a:“H2O”},
{q:“In what year did the Second World War end?”,a:“1945”},
{q:“Which continent is the largest by area?”,a:“Asia”},
];

const NAME5_CATEGORIES = [
{cat:“Things you find in a kitchen”,ex:[“knife”,“spoon”,“pan”,“fridge”,“cutting board”]},
{cat:“Countries in South America”,ex:[“Brazil”,“Argentina”,“Colombia”,“Chile”,“Peru”]},
{cat:“Things that are yellow”,ex:[“banana”,“sun”,“lemon”,“taxi”,“daffodil”]},
{cat:“Famous artists of any kind”,ex:[“Picasso”,“Warhol”,“Beyoncé”,“Shakespeare”,“Da Vinci”]},
{cat:“Animals with stripes”,ex:[“tiger”,“zebra”,“skunk”,“bumblebee”,“chipmunk”]},
{cat:“Things that are red”,ex:[“apple”,“blood”,“fire truck”,“tomato”,“stop sign”]},
{cat:“European capitals”,ex:[“Paris”,“London”,“Berlin”,“Rome”,“Madrid”]},
{cat:“Things in outer space”,ex:[“stars”,“planets”,“black holes”,“astronauts”,“satellites”]},
{cat:“Types of pasta”,ex:[“spaghetti”,“penne”,“fusilli”,“rigatoni”,“linguine”]},
{cat:“Board games”,ex:[“Chess”,“Monopoly”,“Scrabble”,“Cluedo”,“Risk”]},
{cat:“US states that end in the letter A”,ex:[“California”,“Florida”,“Georgia”,“Arizona”,“Nevada”]},
{cat:“Famous paintings”,ex:[“Mona Lisa”,“Starry Night”,“The Scream”,“Girl with a Pearl Earring”,“American Gothic”]},
{cat:“Things with wings”,ex:[“bird”,“bat”,“butterfly”,“plane”,“angel”]},
{cat:“Words that rhyme with night”,ex:[“light”,“might”,“right”,“sight”,“fight”]},
{cat:“Animals that live in the ocean”,ex:[“shark”,“dolphin”,“octopus”,“whale”,“clownfish”]},
{cat:“Movies with one-word titles”,ex:[“Jaws”,“Titanic”,“Psycho”,“Alien”,“Clueless”]},
{cat:“Things you do every morning”,ex:[“brush teeth”,“eat”,“shower”,“check phone”,“panic”]},
{cat:“Types of cheese”,ex:[“cheddar”,“brie”,“gouda”,“feta”,“parmesan”]},
{cat:“Famous duos”,ex:[“Batman and Robin”,“Romeo and Juliet”,“Simon and Garfunkel”,“Bonnie and Clyde”,“salt and pepper”]},
{cat:“Things found at a beach”,ex:[“sand”,“waves”,“seagulls”,“sunscreen”,“shells”]},
{cat:“Shades of blue”,ex:[“navy”,“cobalt”,“turquoise”,“sky blue”,“cerulean”]},
{cat:“Things that go faster than a car”,ex:[“jet”,“rocket”,“bullet”,“cheetah”,“light”]},
{cat:“Things you find at a wedding”,ex:[“cake”,“flowers”,“vows”,“ring”,“speeches”]},
{cat:“Things a Traitor might say”,ex:[“trust me”,“I swear”,“it’s not me”,“why would I”,“I’m literally shaking”]},
{cat:“Things that make a suspicious noise”,ex:[“floorboard”,“phone”,“drawer”,“footsteps”,“silence”]},
];

const EMOJI_CIPHERS = [
{emoji:“🤫🔪🌙”,answer:“Silent murder night”},
{emoji:“🏰👁️🩸”,answer:“Castle sees blood”},
{emoji:“🌹🔥💎”,answer:“Rose fire diamond”},
{emoji:“🎭🗡️🌙”,answer:“Mask dagger moonlight”},
{emoji:“👁️🏹💀”,answer:“Eye arrow death”},
{emoji:“🔮🐺🤫”,answer:“Oracle wolf silence”},
{emoji:“🕯️🗝️🩸”,answer:“Candle key blood”},
{emoji:“🌙🔪👑”,answer:“Night blade crown”},
{emoji:“🦊🤥🏆”,answer:“Fox lies and wins”},
{emoji:“💀🔮🎪”,answer:“Death oracle circus”},
{emoji:“🐉🗡️💎”,answer:“Dragon sword jewel”},
{emoji:“🕵️🌹🔥”,answer:“Spy rose fire”},
{emoji:“🪄💀🤫”,answer:“Magic death whisper”},
{emoji:“🏹🌙🤥”,answer:“Arrow night liar”},
{emoji:“🗝️🩸🏰”,answer:“Key blood castle”},
{emoji:“🎭👁️🌹”,answer:“Mask eye rose”},
{emoji:“🐺🔮💀”,answer:“Wolf oracle death”},
{emoji:“🌙🏆🤫”,answer:“Night champion silence”},
{emoji:“🔪🎭🩸”,answer:“Blade mask blood”},
{emoji:“🦋🗡️👑”,answer:“Butterfly dagger crown”},
];

const WHISPER_PHRASES = [
“The butler did it in the library with the candlestick”,
“Three blind mice ran through the castle gates at midnight”,
“Never trust anyone who smiles during the banishment ceremony”,
“The last one standing always knows exactly what they did”,
“A Traitor among us smiles just a little too much at breakfast”,
“The castle has eyes and the walls have very big ears”,
“Every vote is a confession if you know what to look for”,
“The wolf wears wool and sits at every single round table”,
“Trust no one especially the ones who keep saying trust me”,
“Silence at the right moment is worth more than any alibi”,
“The most dangerous player is the one nobody suspects at all”,
“Lies travel faster than the truth especially before a vote”,
];

const LAST_WORD_CATEGORIES = [
“Things you find in a fridge”, “Animals that live in water”, “Countries in Europe”,
“Things that are round”, “Types of weather”, “Things you do before bed”,
“Sports played with a ball”, “Things you find at a party”, “Words that mean happy”,
“Things that are green”, “Capital cities”, “Types of music”,
“Things you find in a hospital”, “Things that fly”, “Things that are loud”,
“Items in a kitchen drawer”, “Things you say at Christmas”, “Famous fictional villains”,
“Things that are cold”, “Types of transport”, “Things found in a school”,
“Words that rhyme with blue”, “Things that are expensive”, “Animals with four legs”,
“Things you pack for a holiday”, “Types of cake”, “Things found at the beach”,
“Things you do on a Sunday”, “Famous landmarks”, “Things that sparkle”,
];

const RELIC_OBJECTS = [
“A coin”, “A spoon”, “A pen lid”, “A button”, “A hair clip”,
“A paperclip”, “A small stone”, “A bottle cap”, “A ring”,
“A teabag”, “A rubber band”, “A sugar packet”, “A key ring (no key)”,
“A folded piece of paper”, “A small screw”, “A chess piece”,
“A matchstick”, “A dice”, “A sticker”, “A guitar pick”,
];

const MISSIONS = [
// TRIVIA
{ id:“m1”, name:“Castle Trivia”, type:“trivia”, time:12, shieldMode:“hidden_winner”, icon:“📜”,
digital: true, digitalType: “trivia_scored”,
desc:“10 questions shown on the host screen one at a time. Players write answers on paper and reveal simultaneously. After each question, the host marks who got it right. Highest score at the end wins.”,
hostNote:“Use the question panel. Read each question aloud, reveal the answer, then tap who got it correct. Scores are tracked. Award shield to winner silently.” },
{ id:“m2”, name:“Lightning Round”, type:“trivia”, time:8, shieldMode:“public”, icon:“⚡”,
digital: true, digitalType: “trivia_buzzer”,
desc:“Questions flash on the host screen. First player to call out the correct answer wins the point. 10 questions total. Highest score wins a publicly announced shield.”,
hostNote:“Read each question aloud. First to shout the answer — if correct tap their name. If wrong, others can still answer. Announce the winner.” },
// SOCIAL
{ id:“m3”, name:“Two Truths & A Lie”, type:“social”, time:12, shieldMode:“hidden_winner”, icon:“🎭”,
desc:“Each player states 3 facts about themselves. The group votes which is the lie. The person who fools the most people wins — host awards a secret shield.”,
hostNote:“Tally fools privately. Tap the winner silently. No announcement.” },
{ id:“m4”, name:“The Tribunal”, type:“social”, time:15, shieldMode:“hidden_winner”, icon:“⚖️”,
desc:“Three randomly chosen players each have 90 seconds to convince the group they should be trusted. Group votes most convincing. Host awards a hidden shield.”,
hostNote:“Subjective vote — host tallies, awards silently.” },
{ id:“m5”, name:“Secret Ballot”, type:“social”, time:6, shieldMode:“hidden_winner”, icon:“🗳️”,
digital: true, digitalType: “secret_ballot”,
desc:“Everyone privately votes on their phone for one player they would most want to protect. The player with the most nominations wins a hidden shield. No results shown publicly.”,
hostNote:“Host sees all votes on their panel. Award shield to the most nominated player silently.” },
{ id:“m6”, name:“Collective Storytelling”, type:“social”, time:12, shieldMode:“hidden_winner”, icon:“📖”,
desc:“Tell a story round-robin, one sentence each. At the end, the group votes anonymously whose sentence was most suspicious. Player with the fewest votes wins.”,
hostNote:“Collect votes privately. Least-voted player gets the shield — award silently.” },
{ id:“m7”, name:“Trust Fall Vote”, type:“social”, time:6, shieldMode:“all_know”, icon:“🤝”,
desc:“Everyone simultaneously points to who they would most trust in a crisis. Most pointed-at player wins — everyone sees the result.”,
hostNote:“Count pointing fingers simultaneously. Everyone sees — award openly.” },
{ id:“m8”, name:“Forbidden Word”, type:“social”, time:10, shieldMode:“hidden_winner”, icon:“🚫”,
digital: true, digitalType: “forbidden_word”,
desc:“Each player privately receives a unique secret word on their phone that they must not say. During free conversation, try to trick others into saying their word. Last player uncaught wins.”,
hostNote:“Words are pushed secretly to each phone. Your panel shows all words so you can verify eliminations. Tap a player to eliminate them.” },
{ id:“m9”, name:“Human Lie Detector”, type:“social”, time:12, shieldMode:“hidden_winner”, icon:“🤥”,
desc:“Three volunteers each make 3 statements — one is a lie. The group votes who lied best. Best deceiver wins a hidden shield.”,
hostNote:“Group votes, host tallies. Award winner silently.” },
{ id:“m10”, name:“Midnight Auction”, type:“social”, time:6, shieldMode:“public”, icon:“🏺”,
digital: true, digitalType: “auction”,
desc:“Everyone secretly submits a number from 1 to 10 on their phone. Highest unique bid wins. In a tie, both win. All bids revealed publicly after.”,
hostNote:“Bids submitted on player phones. Your panel shows all bids simultaneously. Announce the winner and their bid.” },
// PHYSICAL
{ id:“m11”, name:“Coin Stack Challenge”, type:“physical”, time:7, shieldMode:“public”, icon:“🪙”,
desc:“Balance as many coins as possible on the back of your outstretched hand. Most stacked wins. Result visible to all.”,
hostNote:“Result is obvious — announce and award openly.” },
{ id:“m12”, name:“Freeze Frame”, type:“physical”, time:8, shieldMode:“public”, icon:“🕺”,
desc:“Play music — everyone dances. Stop the music — everyone freezes. Anyone who moves is eliminated. Last standing wins.”,
hostNote:“Elimination is visible to all. Award openly at the end.” },
{ id:“m13”, name:“Whisper Chain”, type:“physical”, time:8, shieldMode:“team_hidden”, icon:“👂”,
digital: true, digitalType: “whisper_chain”,
desc:“Two teams. A secret phrase is sent to the first player on each team. Whisper it down the line. Team whose final player says it most accurately wins — each member gets a hidden shield.”,
hostNote:“Phrase is sent secretly to the first player on each team via the app. Your panel shows the original. Judge accuracy and award each winning team member quietly.” },
{ id:“m14”, name:“Human Knot”, type:“physical”, time:10, shieldMode:“team_hidden”, icon:“🪢”,
desc:“Two teams. Each team holds hands in a circle then tangles arms over and under. First to untangle without releasing hands wins — each member gets a hidden shield.”,
hostNote:“Award each winning team member a shield quietly.” },
{ id:“m15”, name:“Silent Lineup”, type:“physical”, time:6, shieldMode:“all_know”, icon:“🔢”,
desc:“Without speaking or writing, everyone must line up by birthday (day and month). If completed in under 2 minutes, everyone wins a shield. Traitors may subtly cause errors.”,
hostNote:“Either everyone wins or nobody does — announce publicly.” },
{ id:“m16”, name:“Rock Paper Scissors”, type:“physical”, time:8, shieldMode:“public”, icon:“✊”,
digital: true, digitalType: “rps_bracket”,
desc:“A bracketed Rock Paper Scissors tournament. The app generates your matchup bracket. Host calls each match — best of 3. Winner advances. Champion wins a publicly announced shield.”,
hostNote:“App generates the bracket. Call each match, tap the winner to advance them. Champion gets the shield.” },
{ id:“m17”, name:“Mirror Maze”, type:“physical”, time:8, shieldMode:“team_hidden”, icon:“🎯”,
desc:“Pairs race. One is blindfolded, the other guides them verbally through a course. Fastest pair wins — both members get a hidden shield.”,
hostNote:“Fastest pair wins. Award both partners quietly.” },
// PUZZLE
{ id:“m18”, name:“Emoji Cipher”, type:“puzzle”, time:6, shieldMode:“hidden_winner”, icon:“📱”,
digital: true, digitalType: “emoji_cipher”,
desc:“A cryptic phrase appears as emojis on everyone’s screen. First player to whisper the correct translation to the host wins a hidden shield. Everyone sees someone whisper — nobody knows who won.”,
hostNote:“App shows the emoji phrase and the answer on your screen. Award the first correct whisperer silently.” },
{ id:“m19”, name:“The Relic”, type:“puzzle”, time:12, shieldMode:“hidden_winner”, icon:“🗿”,
desc:“The host hides a small object (suggested by the app) somewhere in the space before the mission starts. Players have 4 minutes to find it. If they do, they quietly pocket it and say nothing. After, the group votes who they think found it. The actual finder wins regardless.”,
hostNote:“Use the RELIC BANK in your mission panel to pick an object to hide. You know who found it — they come to you privately. Award that person secretly regardless of what the group votes.”,
digital: true, digitalType: “the_relic” },
{ id:“m20”, name:“Name 5 in 30”, type:“puzzle”, time:8, shieldMode:“public”, icon:“⏱️”,
digital: true, digitalType: “name5”,
desc:“The host announces a category shown on their screen. First player to call out 5 valid items wins that round. 5 rounds total. Most wins takes the shield — announced publicly.”,
hostNote:“App shows the category. First to call 5 correct answers wins the round. Track wins — announce overall winner.” },
// LUCK
{ id:“m21”, name:“The Draw”, type:“luck”, time:3, shieldMode:“hidden_winner”, icon:“🎴”,
digital: true, digitalType: “the_draw”,
desc:“The app secretly and randomly selects one player as the winner. No ceremony, no visible result. The winner receives a silent notification on their phone. Nobody else will ever know who won or why.”,
hostNote:“App picks a winner at random and notifies them privately. You also see who won on your panel. Award the shield silently — they already know.” },
{ id:“m22”, name:“Hot Take”, type:“luck”, time:6, shieldMode:“public”, icon:“🔥”,
digital: true, digitalType: “hot_take”,
desc:“The host reads a controversial statement from the app. Everyone votes Agree or Disagree on their phone simultaneously. Players on the majority side win a shield — announced publicly.”,
hostNote:“App shows the hot take. Players vote on phones. App calculates majority. Award shields to all players on the winning side.” },
// DRAMA
{ id:“m23”, name:“The Monologue”, type:“drama”, time:15, shieldMode:“hidden_winner”, icon:“🎤”,
desc:“Each player gives a 60-second speech on why they should be trusted. Group votes anonymously. Most convincing wins a hidden shield.”,
hostNote:“Collect votes privately. Award the winner without revealing the tally.” },
{ id:“m24”, name:“Last Word”, type:“drama”, time:8, shieldMode:“public”, icon:“💬”,
desc:“The host announces a category from the app’s built-in bank. Players take turns saying one item each. If you hesitate for more than 3 seconds, repeat an answer, or go blank — you’re eliminated. Last player standing wins.”,
hostNote:“Use the LAST WORD BANK in your mission panel — tap a category to display it. You judge hesitation and repeats. Point at eliminated players. Last one wins — announce and award openly.”,
digital: true, digitalType: “last_word” },
// SEER MISSION — always assigned as the Seer mission
{ id:“m25”, name:“The Witness”, type:“social”, time:12, shieldMode:“seer_award”, icon:“👁️”,
digital: true, digitalType: “the_witness”,
desc:“Five questions about real events that have happened in this game — answered privately on your phone. Highest score wins the Seer power. Results are never announced. The Seer discovers their power silently.”,
hostNote:“Questions are generated from the actual game history. Players answer privately. You see all scores. When there is a winner, award the Seer — a private message confirms to the winner only. No announcement.” },
];

const HOT_TAKES = [
“Pineapple on pizza is genuinely good and people who disagree are cowards”,
“A hot dog is a sandwich and you cannot convince me otherwise”,
“Die Hard is a Christmas movie”,
“Cats are better pets than dogs”,
“Cereal is a soup”,
“The person who talks the most at the Round Table is always suspicious”,
“The best strategy in this game is to never speak first”,
“It is always better to banish too early than too late”,
“You should always trust your gut over logic in this game”,
“The quiet player is more dangerous than the loud one”,
“People who have been on reality TV are worse at this game not better”,
“Traitors always give themselves away at breakfast”,
“Reading faces is more reliable than listening to what people say”,
“The funniest player in a group is statistically the most likely to be lying”,
“People are more honest when they think nobody is watching”,
“First impressions in this game are almost always wrong”,
“The best liars are the ones who believe their own lies”,
“You can always tell who voted for you even when it’s anonymous”,
“Alliances formed before the first vote always fall apart”,
“The host of a party is never really trusted at their own party”,
];

export {
  TRIVIA_BANK,
  NAME5_CATEGORIES,
  EMOJI_CIPHERS,
  WHISPER_PHRASES,
  LAST_WORD_CATEGORIES,
  RELIC_OBJECTS,
  MISSIONS,
  HOT_TAKES,
};
